### ISSUE TITLE
Elm debugger performance

### ISSUE THREAD

**Issue by absynce** [w0rm/elm-pool#8]
When compiled with `--debug`, that is, using the Elm debugger, it causes the game to run sluggishly while simulating.

**Comment by ianmackenzie** [comment]
If there are large data structures (meshes etc.) stored in the model then the debugger will definitely slow things down since it will attempt to introspect those data structures (and built up a large corresponding 'expando' data structure) on every call to `update`. The trick I've used is to 'hide' those data structures in a function, because the debugger won't introspect functions. So instead of having

```elm
type alias Model =
    { someLargeThing : SomeType
    }
```

you can use something like this instead:

```elm
type alias Model =
    { someLargeThing : () -> SomeType
    }

-- Updating
updatedModel =
    { model | someLargeThing = always updatedThing }

-- Accessing
thing =
    model.someLargeThing ()
```

**Comment by w0rm** [comment]
@absynce since we've removed entities from each physical body in the model, there are less things for debugger to render. It is still slow, but I'd rather have it slow than not be able to debug physics.

Hope you're OK with me closing this issue

**Comment by absynce** [comment]
@w0rm sounds good to me. 👍 I agree we need to be able to debug physics.
